name: adventofcode2021
version: 0.0.1
synopsis: advent of code 2021 solutions
description: solutions
maintainer: David Fontenot

ghc-options: -Wall

default-extensions:
  - OverloadedStrings

dependencies:
  - base
  - megaparsec
  - mtl
  - parsec
  - split
  - text
  - unordered-containers
  - vector

executables:
  day1:
    main: day1.hs
    source-dirs: .

  day2:
    main: day2.hs
    source-dirs: .

  day3:
    main: day3.hs
    source-dirs: .

  day3part2:
    main: day3-part2.hs
    source-dirs: .

  day4:
    main: day4.hs
    source-dirs: .

  day5:
    main: day5.hs
    source-dirs: .
    #ghc-options: [-XTypeSynonymInstances]

